// GENERATED by design/gen_tokens.dart from design/tokens.json.
// Do not edit by hand.
// ignore_for_file: constant_identifier_names

import 'dart:ui';

class LcPalette {
  final String id;
  final String name;
  final bool dark;
  final Color bg;
  final Color surface;
  final Color ink;
  final Color muted;
  final Color line;
  final Color track;
  final Color accent;
  final Color onAccent;
  final Color accentSoft;
  final Color coin;
  final Color coinSoft;
  final Color good;
  final Color goodSoft;
  final Color warn;
  final Color warnSoft;

  const LcPalette({
    required this.id,
    required this.name,
    required this.dark,
    required this.bg,
    required this.surface,
    required this.ink,
    required this.muted,
    required this.line,
    required this.track,
    required this.accent,
    required this.onAccent,
    required this.accentSoft,
    required this.coin,
    required this.coinSoft,
    required this.good,
    required this.goodSoft,
    required this.warn,
    required this.warnSoft,
  });
}

abstract final class LcTokens {
  static const String defaultTheme = 'matcha';

  static const Map<String, LcPalette> themes = {
    'matcha': LcPalette(
      id: 'matcha',
      name: 'มัทฉะ',
      dark: false,
      bg: Color(0xFFF5F6F2),
      surface: Color(0xFFFFFFFF),
      ink: Color(0xFF1B211E),
      muted: Color(0xFF58625D),
      line: Color(0xFFE4E7E2),
      track: Color(0xFFE5E9E4),
      accent: Color(0xFF2A7162),
      onAccent: Color(0xFFFFFFFF),
      accentSoft: Color(0xFFE2EFEA),
      coin: Color(0xFF8F5C10),
      coinSoft: Color(0xFFF7EEDC),
      good: Color(0xFF2B7A4B),
      goodSoft: Color(0xFFE3F1E7),
      warn: Color(0xFFA5501B),
      warnSoft: Color(0xFFFAEBDD),
    ),
    'sakura': LcPalette(
      id: 'sakura',
      name: 'ซากุระ',
      dark: false,
      bg: Color(0xFFFAF5F6),
      surface: Color(0xFFFFFFFF),
      ink: Color(0xFF2A1D22),
      muted: Color(0xFF6A5B60),
      line: Color(0xFFEDE3E6),
      track: Color(0xFFEFE6E9),
      accent: Color(0xFFA8455F),
      onAccent: Color(0xFFFFFFFF),
      accentSoft: Color(0xFFF6E3E8),
      coin: Color(0xFF8F5C10),
      coinSoft: Color(0xFFF7EEDC),
      good: Color(0xFF2B7A4B),
      goodSoft: Color(0xFFE3F1E7),
      warn: Color(0xFFA5501B),
      warnSoft: Color(0xFFFAEBDD),
    ),
    'mono': LcPalette(
      id: 'mono',
      name: 'ขาวดำ (โฟกัส)',
      dark: false,
      bg: Color(0xFFF4F4F4),
      surface: Color(0xFFFFFFFF),
      ink: Color(0xFF111111),
      muted: Color(0xFF575757),
      line: Color(0xFFE0E0E0),
      track: Color(0xFFE2E2E2),
      accent: Color(0xFF111111),
      onAccent: Color(0xFFFFFFFF),
      accentSoft: Color(0xFFEAEAEA),
      coin: Color(0xFF333333),
      coinSoft: Color(0xFFEAEAEA),
      good: Color(0xFF111111),
      goodSoft: Color(0xFFEAEAEA),
      warn: Color(0xFF111111),
      warnSoft: Color(0xFFEAEAEA),
    ),
    'dark': LcPalette(
      id: 'dark',
      name: 'มืด',
      dark: true,
      bg: Color(0xFF111413),
      surface: Color(0xFF1B1F1D),
      ink: Color(0xFFECF0EE),
      muted: Color(0xFFA2ABA6),
      line: Color(0xFF2A2F2C),
      track: Color(0xFF2A2F2C),
      accent: Color(0xFF72C4AB),
      onAccent: Color(0xFF0D1411),
      accentSoft: Color(0xFF1F302A),
      coin: Color(0xFFE2B45C),
      coinSoft: Color(0xFF33291A),
      good: Color(0xFF7FCB98),
      goodSoft: Color(0xFF1D2E23),
      warn: Color(0xFFE89C69),
      warnSoft: Color(0xFF35261C),
    ),
  };

  static const double displaySize = 28.0;
  static const int displayWeight = 700;
  static const double titleSize = 20.0;
  static const int titleWeight = 700;
  static const double bodySize = 16.0;
  static const int bodyWeight = 400;
  static const double labelSize = 14.0;
  static const int labelWeight = 500;
  static const double captionSize = 12.0;
  static const int captionWeight = 400;
  static const double jpPromptSize = 64.0;
  static const int jpPromptWeight = 700;
  static const double jpAnswerSize = 48.0;
  static const int jpAnswerWeight = 700;
  static const double jpSentenceSize = 20.0;
  static const int jpSentenceWeight = 500;

  static const double radiusCard = 24.0;
  static const double radiusCardLarge = 28.0;
  static const double radiusButton = 18.0;
  static const double radiusControl = 14.0;
  static const double radiusPill = 999.0;

  static const double spacingXs = 4.0;
  static const double spacingSm = 8.0;
  static const double spacingMd = 12.0;
  static const double spacingLg = 16.0;
  static const double spacingXl = 20.0;
  static const double spacingXxl = 24.0;

  static const int motionFastMs = 150;
  static const int motionNormalMs = 250;
  static const double touchTargetMin = 44.0;
}
