// Generates app/lib/ui/tokens.g.dart from design/tokens.json.
//
//   dart run design/gen_tokens.dart          # write the file
//   dart run design/gen_tokens.dart --check  # fail if the file is stale (CI)
import 'dart:convert';
import 'dart:io';

void main(List<String> args) {
  final root = File(Platform.script.toFilePath()).parent.parent;
  final json = jsonDecode(File('${root.path}/design/tokens.json')
      .readAsStringSync()) as Map<String, dynamic>;
  final out = File('${root.path}/app/lib/ui/tokens.g.dart');
  final code = generate(json);
  if (args.contains('--check')) {
    if (!out.existsSync() || out.readAsStringSync() != code) {
      stderr.writeln('app/lib/ui/tokens.g.dart is stale: '
          'run `dart run design/gen_tokens.dart`');
      exit(1);
    }
    stdout.writeln('tokens.g.dart is up to date');
    return;
  }
  out.writeAsStringSync(code);
  stdout.writeln('wrote ${out.path}');
}

String generate(Map<String, dynamic> j) {
  final themes = (j['themes'] as Map<String, dynamic>);
  final colorNames =
      ((themes.values.first as Map)['colors'] as Map).keys.cast<String>();
  final b = StringBuffer()
    ..writeln('// GENERATED by design/gen_tokens.dart from design/tokens.json.')
    ..writeln('// Do not edit by hand.')
    ..writeln('// ignore_for_file: constant_identifier_names')
    ..writeln()
    ..writeln("import 'dart:ui';")
    ..writeln()
    ..writeln('class LcPalette {')
    ..writeln('  final String id;')
    ..writeln('  final String name;')
    ..writeln('  final bool dark;');
  for (final c in colorNames) {
    b.writeln('  final Color $c;');
  }
  b
    ..writeln()
    ..writeln('  const LcPalette({')
    ..writeln('    required this.id,')
    ..writeln('    required this.name,')
    ..writeln('    required this.dark,');
  for (final c in colorNames) {
    b.writeln('    required this.$c,');
  }
  b
    ..writeln('  });')
    ..writeln('}')
    ..writeln()
    ..writeln('abstract final class LcTokens {')
    ..writeln("  static const String defaultTheme = '${j['defaultTheme']}';")
    ..writeln()
    ..writeln('  static const Map<String, LcPalette> themes = {');
  themes.forEach((id, t) {
    final colors = (t['colors'] as Map<String, dynamic>);
    b
      ..writeln("    '$id': LcPalette(")
      ..writeln("      id: '$id',")
      ..writeln("      name: '${t['name']}',")
      ..writeln("      dark: ${t['brightness'] == 'dark'},");
    for (final c in colorNames) {
      final hex = (colors[c] as String).substring(1).toUpperCase();
      b.writeln('      $c: Color(0xFF$hex),');
    }
    b.writeln('    ),');
  });
  b.writeln('  };');

  final typo = j['typography'] as Map<String, dynamic>;
  b.writeln();
  (typo['scale'] as Map<String, dynamic>).forEach((name, v) {
    b
      ..writeln('  static const double ${name}Size = ${_num(v['size'])};')
      ..writeln('  static const int ${name}Weight = ${v['weight']};');
  });
  for (final section in ['radius', 'spacing']) {
    b.writeln();
    (j[section] as Map<String, dynamic>).forEach((k, v) {
      b.writeln('  static const double $section${_cap(k)} = ${_num(v)};');
    });
  }
  b.writeln();
  (j['motion'] as Map<String, dynamic>).forEach((k, v) {
    b.writeln('  static const int motion${_cap(k)} = $v;');
  });
  b
    ..writeln('  static const double touchTargetMin = ${_num(j['touchTargetMin'])};')
    ..writeln('}');
  return b.toString();
}

String _cap(String s) => s[0].toUpperCase() + s.substring(1);
String _num(Object? v) => (v as num).toDouble().toString();
